# Generated by Django 2.2.1 on 2019-05-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(max_length=300)),
                ('order_status_marketplace', models.CharField(max_length=100)),
                ('order_status_lengow', models.CharField(max_length=100)),
                ('order_id', models.CharField(max_length=300, unique=True)),
                ('order_purchase_date', models.DateTimeField()),
                ('billing_email', models.EmailField(max_length=300)),
                ('delivery_full_address', models.CharField(max_length=300)),
                ('first_product_title', models.CharField(max_length=300)),
                ('first_product_category', models.CharField(max_length=300)),
                ('first_product_url_image', models.URLField(max_length=1000)),
                ('registery_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
