# Generated by Django 2.2.1 on 2019-05-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_email',
            field=models.EmailField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_full_address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_product_category',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_product_title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_product_url_image',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_purchase_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status_lengow',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status_marketplace',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='registery_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
